# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
  release:
    types: [created]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      # packages: write # 不需要发布到 GitHub Packages，所以可以移除此权限

    steps:
    - uses: actions/checkout@v4

    # 1. 修改 Java 版本为 21
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21' # 将 '11' 修改为 '21'
        distribution: 'temurin'
        # server-id: github # 如果不发布到 GitHub Packages，这些与 Maven settings.xml 相关的行可以移除
        # settings-path: ${{ github.workspace }} # 同上

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    # 2. 移除发布到 GitHub Packages 的步骤
    # - name: Publish to GitHub Packages Apache Maven
    #  run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml
    #  env:
    #    GITHUB_TOKEN: ${{ github.token }}

    # 3. 添加将构建产物上传到 GitHub Release 的步骤
    - name: Upload Plugin to GitHub Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # 使用内置的 GITHUB_TOKEN
      with:
        upload_url: ${{ github.event.release.upload_url }} # 获取 Release 的上传 URL
        asset_path: ./target/YourPlugin-1.0-SNAPSHOT.jar # 替换为你的插件 JAR 文件的实际路径和名称
        asset_name: YourPlugin-${{ github.event.release.tag_name }}.jar # 建议的命名方式：插件名-版本号.jar
        asset_content_type: application/java-archive # JAR 文件的 MIME 类型
